# Site settings
title: "doing one note at a time"
description: "Blog site with support for Latex!!!"
url: "https://webhash.github.io/"
author:
  name: "webhash"
  url: "https://github.com/webhash/"

# Build settings
baseurl: https://webhash.github.io/
source: .
destination: ./_site
permalink: :title/
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
genre: "Notes" # Blog genre
version: "0.0.1"    # Blog site version


# Options: Define which header/footer to use
custom_header: false
custom_nav_footer: false
reverse: false

# Plugins
plugins:
  - jekyll-paginate
